def bsearch(data,target):
  min=0;
  max=len(data)-1;
  while(True):
      mid=(min+max)//2;
      if(data[min]==target):
        print(min);
        break;
      elif(data[max]==target):
        print(max);
        break;
      elif(abs(min-max)==1):
        print('None');
        break;
      elif(data[mid]==target):
        print(mid);
        break;
      else:
        if(data[mid]>target):
          max=mid;
        else:
          min=mid;
